### ISSUE TITLE
Color palette and "Skills" layout

### ISSUE THREAD

**Issue by annalissette** [FrankcoMiguel/Portfolio#1]
Hey, Frank!
I believe that you need to improve the harmony between the colors you use. 
There are lots of sites where you can find palette recommendations that fit your aesthetic. 
I found one at color.adobe that I think matches what you were trying to achieve:
![1](https://user-images.githubusercontent.com/59299795/72117367-cf1ede00-3323-11ea-8122-99b1f9dc91e6.JPG) By: Kelsie McGilvray

As for the Skills section layout, I think you can contain the logos individually in rectangles of a color that makes contrast with the background, to avoid both the logo getting lost in the background and it looking uneven. 

You have a lot of potential and you sure know what a modern design looks like. Keep it up!

**Comment by FrankcoMiguel** [comment]
I really appreciate that.
Thanks for the recommendation, since now I'll be using these colors.

I'm also working on a Chicken Delivery Application and I really need a designer, how about you??

**Comment by FrankcoMiguel** [comment]
So I'm gonna create a new branch, only to deal with this issue specifically.

**Comment by FrankcoMiguel** [comment]
The pull request is already open, any suggestions must be added on  'color palette enhancement' [Pull Request]
