### ISSUE TITLE
Image Link tags broken

### ISSUE THREAD

**Issue by rkp2222573** [FrankcoMiguel/Portfolio#7]
Hey 👋,

i just checked out your portfolio and all of the image links are broken.

Best of luck

**Comment by FrankcoMiguel** [comment]
Thanks mate, I decided to change the whole design, as you can see am currently working on a new branch called gastby-feature

So I was creating the version 2 using pure React.js and Webpack 4, but now am using Gatsby.js which is a nice framework (very very straightforward).

**Comment by FrankcoMiguel** [comment]
Here's one of the Pages

![About](https://user-images.githubusercontent.com/41207024/90561706-94004b00-e14d-11ea-88bb-33cc5d197cbf.png)

**Comment by rkp2222573** [comment]
Really nice design bro, i like the direction that you are taking it.

**Comment by FrankcoMiguel** [comment]
Thanks bro, what are you up to?

**Comment by rkp2222573** [comment]
Write now i'm preparing to release my beta for a start-up with me and my brother 😄 How about you? btw do you have discord?

**Comment by FrankcoMiguel** [comment]
That's awesome man. I wish the best for you guys!

Here is my discord: #2715Mr_Chute
